### PR TITLE
Prefix PULL_REQUEST_ID like other ENVs

### PR DESCRIPTION
**Pull request by doomspork**
@mmozuras I noticed this the other day when making some changes to Nag (btw, development has shifted to my repo: https://github.com/doomspork/nag).

Let me know your thoughts 👍

### CODE REVIEW

**Comment by doomspork** [comment]
Fixed the failing test @mmozuras, sorry about that.

**Comment by mmozuras** [comment]
@doomspork 👍 

Just one thing: the last time we've changed the names of ENV variables, we broke some builds. Here's [one example](https://github.com/mmozuras/pronto/issues/219#issuecomment-292519929) by @sauliusgrigaitis. What could we do to inform our users this time? Maybe a post-install message? What do you think?

**Comment by doomspork** [comment]
@mmozuras maybe we can deprecate the `PULL_REQUEST_ID`?  We look it up first, if it has a value, we print out a deprecation warning and urge them to use `PRONTO_PULL_REQUEST_ID`.  Whatcha think?

**Comment by mmozuras** [comment]
@doomspork 👍

**Comment by doomspork** [comment]
@mmozuras updated, let me know whatcha think 😀

**Comment by doomspork** [comment]
I'm not 100% why those tests are failing for certain versions, I cannot re-produce the failures locally.

**Comment by mmozuras** [comment]
@doomspork I'm not sure either. But I found this in the log:

screenshot 2017-04-19 23 31 45

Something is definitely wrong, not sure what 😄

**Comment by doomspork** [comment]
@mmozuras I know, it's quiet weird.  I searched through the project and can find no other mentions of `PULL_REQUEST_ID`.

**Comment by mmozuras** [comment]
@doomspork maybe it's something with Travis then. Trying to figure it out too 😄

**Comment by doomspork** [comment]
@mmozuras maybe Travis is caching the old ENV from `.travis.yml`.  Is it possible to re-start the build?  Are you using caching with the builds?

**Comment by doomspork** [comment]
Thanks @mmozuras! 👍

**Pull request merged**
