### PR TITLE
Make gitlab work with ssh port urls `ssh://user@url.com:123/path/to/repo`

### PR DESCRIPTION
**Pull request by doits**
Just a simple change with spec to make it work with ssh port urls.

### CODE REVIEW

**Comment by doits** [comment]
looks like travis got an error and it failed, but not because of a spec

**Comment by mmozuras** [comment]
@doits could you rebase against master?

**Comment by doits** [comment]
done

**Comment by mmozuras** [comment]
@doits thanks! :bow:

**Pull request merged**
